### ISSUE TITLE
GPU gave incorect result!

### ISSUE THREAD

**Issue by edwinosky** [tao-foundation/teominer#1]
![captura](https://user-images.githubusercontent.com/26192834/47674166-1260b700-db8d-11e8-8632-716cf09b4f40.PNG)

**Comment by edwinosky** [comment]
amd rx5xx and rx 4xx cards, proado in windows and ubuntu 18, tested with the release version and also compiled by myself and always gives the same error

**Comment by trustfarm-dev** [comment]
@edwinosky  thanks for information.

Also that problem reported on AMD.
There's OpenCL code has errors.
Just patched now. v0.16.3 
Can you check it again? thanks.

**Comment by edwinosky** [comment]
ready friend, now everything works correctly, thanks for such fast assistance

**Comment by trustfarm-dev** [comment]
@edwinosky  is this your wallet ?
0xf6c7bb1ef14418816529e186c1692c55e6cc0f1a
it is whitelisted now.

On this pre-test-mainnet will be restart real mainnet on this night. 
You can mine early access on TEO VIP mainnet. 2~3weeks later this mainnet will be public open
thanks.

**Comment by edwinosky** [comment]
If that's my wallet, give me the instructions to access TEO VIP

**Comment by trustfarm-dev** [comment]
Mining is same . If Wallet address is not in whitelist , no payout.
I have added whitelist , above address.
If above wallet is personal wallet (generate in myetherwallet or wallet.tao.foundation or variants) it  can compatible.

Or leave wallet address if you want to use another.
Thanks
